---
- name: Create symbolic link from Python3 to Python
  file:
    src: "/usr/bin/python3"
    dest: "/usr/bin/python"
    state: link

- name: Install pip apt package and update
  apt:
    name: python3-pip
    state: present
    update_cache: yes